### ISSUE TITLE
subfieldChar includes punctuation as well as alphanumeric?

### ISSUE THREAD

**Issue by dmolesUC** [MARCspec/MARCspec#31]
According to the [MARC 21](https://www.loc.gov/marc/bibliographic/bdintro.html) bibliographic standard as well as [UNIMARC 2008], a subfield code can only be alphabetic or numeric (MARC 21 specifies lower-case alphabetic). However, the grammar defines `subfieldChar` and `subfieldCode` as:

```ABNF
subfieldChar      = %x21-3F / %x5B-7B / %x7D-7E
                    ; ! " # $ % & ' ( ) * + , - . / 0-9 : ; < = > ? [ \ ] ^ _ \` a-z { } ~
subfieldCode      = "$" subfieldChar
```

Is this intentional? Do non-bibliographic MARC use cases include punctuation as subfield codes?

**Comment by phochste** [comment]
I don't know if this is intentional. 

For my use-cases I use MARCSpec not as a validating parser, but a way to process any type of MARC input that is out there in the wild. And there are edge-cases that need to be fixed. If MARCSpec would break on this weird cases, then I still need to create my own code to parse those records and fix them.

It can maybe be compared with HMTL parser that can have a 'strict' or 'lax' processing modes.

**Comment by dmolesUC** [comment]
That makse sense. And after doing some more reading, it looks like the [general spec](https://www.loc.gov/marc/specifications/specrecstruc.html) doesn't prohibit these characters (and in fact doesn't limit subfield codes to a single character.) I'll close the issue.
